// Generated by cbindgen from crates/waffle-ffi/src/lib.rs — do not edit.

#ifndef WAFFLE_H
#define WAFFLE_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

typedef struct WfDoc WfDoc;

typedef struct {
  uint32_t r0;
  uint32_t c0;
  uint32_t r1;
  uint32_t c1;
} WfRect;

/**
 * One visible cell. `text_off/len` index into the fetch text buffer.
 */
typedef struct {
  uint32_t text_off;
  uint32_t text_len;
  uint32_t style;
  /**
   * 0 = use the style's colour, else 0xFF000000 | rgb from the number format.
   */
  uint32_t color;
  uint8_t kind;
  uint8_t align;
  uint8_t flags;
  /**
   * Conditional formatting: 1 bold, 2 italic, 4 strikethrough, 8 underline.
   */
  uint8_t cf_flags;
  /**
   * Conditional fill / font colour (0 = none, else 0xFF000000 | rgb).
   */
  uint32_t cf_fill;
  uint32_t cf_font;
  /**
   * Data bar colour and length (0 = none, else 1…1000 of the cell width).
   */
  uint32_t bar_color;
  uint32_t bar;
} WfCell;

typedef struct {
  /**
   * UTF-8 byte range in the cell text.
   */
  uint32_t start;
  uint32_t end;
  /**
   * -1 inherit, 0 off, 1 on
   */
  int8_t bold;
  int8_t italic;
  int8_t underline;
  int8_t strike;
  /**
   * 0 = inherit
   */
  float size;
  /**
   * 0 = inherit, else 0xFF000000 | rgb
   */
  uint32_t color;
} WfRun;

typedef struct {
  /**
   * 0 image, 1 chart
   */
  uint32_t kind;
  uint32_t row0;
  uint32_t col0;
  double dx0;
  double dy0;
  /**
   * Whether (row1, col1, dx1, dy1) is set; otherwise use width/height.
   */
  bool two_cell;
  uint32_t row1;
  uint32_t col1;
  double dx1;
  double dy1;
  double width;
  double height;
} WfDrawing;

typedef struct {
  float font_size;
  /**
   * 0 = automatic, else 0xFF000000 | rgb
   */
  uint32_t text_color;
  uint32_t fill_color;
  uint8_t bold;
  uint8_t italic;
  uint8_t underline;
  uint8_t strike;
  /**
   * 0 general, 1 left, 2 center, 3 right, 4 fill, 5 justify, 6 centerContinuous, 7 distributed
   */
  uint8_t halign;
  /**
   * 0 bottom, 1 center, 2 top, 3 justify, 4 distributed
   */
  uint8_t valign;
  uint8_t wrap;
  uint8_t indent;
  /**
   * left, right, top, bottom; see styles::BORDER_STYLES
   */
  uint8_t border_style[4];
  uint32_t border_color[4];
  int16_t rotation;
  uint8_t is_date;
  uint8_t is_percent;
} WfStyle;

typedef struct {
  uint64_t count;
  uint64_t numbers;
  double sum;
  double min;
  double max;
} WfStats;

WfDoc *wf_open(const char *path);

/**
 * Error from the last failed `wf_open` on this thread.
 */
const char *wf_open_error(void);

WfDoc *wf_new(void);

void wf_close(WfDoc *d);

uint32_t wf_progress(WfDoc *d);

bool wf_loaded(WfDoc *d);

/**
 * Load error (if any), consumed once.
 */
const char *wf_take_load_error(WfDoc *d);

/**
 * Last error from an edit or save.
 */
const char *wf_error(WfDoc *d);

/**
 * 0 xlsx, 1 xlsm, 2 csv, 3 import-only (xls/xlsb/ods), 4 new
 */
uint32_t wf_format(WfDoc *d);

bool wf_save(WfDoc *d, const char *path, bool csv);

bool wf_edited(WfDoc *d);

uint64_t wf_memory(WfDoc *d);

uint32_t wf_sheet_count(WfDoc *d);

const char *wf_sheet_name(WfDoc *d, uint32_t i);

/**
 * 0 visible, 1 hidden, 2 very hidden
 */
uint32_t wf_sheet_visibility(WfDoc *d, uint32_t i);

bool wf_sheet_loaded(WfDoc *d, uint32_t i);

uint32_t wf_active_sheet(WfDoc *d);

void wf_set_active_sheet(WfDoc *d, uint32_t i);

int32_t wf_add_sheet(WfDoc *d, uint32_t at);

bool wf_rename_sheet(WfDoc *d, uint32_t i, const char *name);

bool wf_delete_sheet(WfDoc *d, uint32_t i);

bool wf_move_sheet(WfDoc *d, uint32_t from, uint32_t to);

bool wf_set_sheet_hidden(WfDoc *d, uint32_t i, bool hidden);

/**
 * Most rows the sheet may have (Excel's limit for workbooks, unbounded for CSV).
 */
uint32_t wf_max_rows(WfDoc *d, uint32_t si);

uint32_t wf_rows(WfDoc *d, uint32_t si);

uint32_t wf_cols(WfDoc *d, uint32_t si);

uint32_t wf_data_rows(WfDoc *d, uint32_t si);

uint32_t wf_data_cols(WfDoc *d, uint32_t si);

double wf_row_y(WfDoc *d, uint32_t si, uint32_t r);

double wf_col_x(WfDoc *d, uint32_t si, uint32_t c);

uint32_t wf_row_at(WfDoc *d, uint32_t si, double y);

uint32_t wf_col_at(WfDoc *d, uint32_t si, double x);

double wf_total_height(WfDoc *d, uint32_t si);

double wf_total_width(WfDoc *d, uint32_t si);

uint32_t wf_freeze_rows(WfDoc *d, uint32_t si);

uint32_t wf_freeze_cols(WfDoc *d, uint32_t si);

/**
 * The sheet's view hides gridlines (xlsx `showGridLines="0"`).
 */
bool wf_hide_gridlines(WfDoc *d, uint32_t si);

bool wf_row_hidden(WfDoc *d, uint32_t si, uint32_t r);

bool wf_col_hidden(WfDoc *d, uint32_t si, uint32_t c);

bool wf_row_filtered(WfDoc *d, uint32_t si, uint32_t r);

bool wf_has_formula(WfDoc *d, uint32_t si, uint32_t r, uint32_t c);

bool wf_is_blank(WfDoc *d, uint32_t si, uint32_t r, uint32_t c);

/**
 * Merges intersecting a rectangle; returns how many were written (≤ max).
 */
uint32_t wf_merges(WfDoc *d, uint32_t si, WfRect area, WfRect *outp, uint32_t max);

/**
 * Merge containing a cell, if any.
 */
bool wf_merge_at(WfDoc *d, uint32_t si, uint32_t r, uint32_t c, WfRect *outp);

/**
 * Fill the cell buffer for a rectangle. Pointers stay valid until the next fetch.
 */
uint32_t wf_fetch(WfDoc *d, uint32_t si, WfRect area, const WfCell **cells, const uint8_t **text);

const char *wf_edit_text(WfDoc *d, uint32_t si, uint32_t r, uint32_t c);

const char *wf_display_text(WfDoc *d, uint32_t si, uint32_t r, uint32_t c);

/**
 * Excel's Cmd+Arrow: jump to the edge of the current data region.
 */
void wf_jump(WfDoc *d,
             uint32_t si,
             uint32_t r,
             uint32_t c,
             int32_t dr,
             int32_t dc,
             uint32_t *r_out,
             uint32_t *c_out);

/**
 * Formatting runs of a rich-text cell; font names via `wf_run_font`.
 */
uint32_t wf_runs(WfDoc *d, uint32_t si, uint32_t r, uint32_t c, WfRun *outp, uint32_t max);

const char *wf_run_font(WfDoc *d, uint32_t si, uint32_t r, uint32_t c, uint32_t i);

uint32_t wf_drawing_count(WfDoc *d, uint32_t si);

bool wf_drawing(WfDoc *d, uint32_t si, uint32_t i, WfDrawing *outp);

/**
 * Image path (for images) or title (for charts).
 */
const char *wf_drawing_ref(WfDoc *d, uint32_t si, uint32_t i);

/**
 * Bytes of a part inside the original package (e.g. an image). Valid until the next call.
 */
const uint8_t *wf_part_bytes(WfDoc *d, const char *path, size_t *len);

uint32_t wf_style_generation(WfDoc *d);

uint32_t wf_style_count(WfDoc *d);

void wf_style(WfDoc *d, uint32_t id, WfStyle *outp);

const char *wf_style_font_name(WfDoc *d, uint32_t id);

const char *wf_style_numfmt(WfDoc *d, uint32_t id);

/**
 * xf used by a cell (for toolbar state).
 */
uint32_t wf_cell_style(WfDoc *d, uint32_t si, uint32_t r, uint32_t c);

/**
 * kind: 0 bold, 1 italic, 2 underline, 3 strike, 4 font size (num), 5 font name (text),
 * 6 text colour (num rgb, <0 = automatic), 7 fill (num rgb, <0 = none), 8 number format (text),
 * 9 horizontal align (num), 10 vertical align (num), 11 wrap (num 0/1),
 * 12 borders: num = style, text = "ltrb" sides (subset), color via `color` (<0 automatic).
 */
bool wf_apply_style(WfDoc *d,
                    uint32_t si,
                    const WfRect *rs,
                    uint32_t n,
                    uint32_t kind,
                    double num,
                    const char *text,
                    double color);

bool wf_set_input(WfDoc *d, uint32_t si, uint32_t r, uint32_t c, const char *text);

bool wf_set_input_range(WfDoc *d, uint32_t si, WfRect rect, const char *text);

/**
 * what: 0 contents, 1 formats, 2 all
 */
bool wf_clear(WfDoc *d, uint32_t si, const WfRect *rs, uint32_t n, uint32_t what);

bool wf_insert_rows(WfDoc *d, uint32_t si, uint32_t at, uint32_t n);

bool wf_delete_rows(WfDoc *d, uint32_t si, uint32_t at, uint32_t n);

bool wf_insert_cols(WfDoc *d, uint32_t si, uint32_t at, uint32_t n);

bool wf_delete_cols(WfDoc *d, uint32_t si, uint32_t at, uint32_t n);

bool wf_set_col_width(WfDoc *d, uint32_t si, uint32_t c0, uint32_t c1, double px);

bool wf_set_row_height(WfDoc *d, uint32_t si, uint32_t r0, uint32_t r1, double px);

/**
 * axis: 0 rows, 1 cols
 */
bool wf_set_hidden(WfDoc *d, uint32_t si, uint32_t axis, uint32_t a0, uint32_t a1, bool hidden);

bool wf_set_freeze(WfDoc *d, uint32_t si, uint32_t rows, uint32_t cols);

bool wf_merge(WfDoc *d, uint32_t si, WfRect rect);

bool wf_unmerge(WfDoc *d, uint32_t si, WfRect rect);

bool wf_fill(WfDoc *d, uint32_t si, WfRect rect, bool down);

bool wf_fill_from(WfDoc *d, uint32_t si, WfRect src, WfRect target);

bool wf_undo(WfDoc *d, uint32_t *sheet_out);

bool wf_redo(WfDoc *d, uint32_t *sheet_out);

const char *wf_undo_label(WfDoc *d);

const char *wf_redo_label(WfDoc *d);

bool wf_sort(WfDoc *d,
             uint32_t si,
             uint32_t r0,
             uint32_t r1,
             const uint32_t *cols,
             const bool *asc,
             uint32_t n);

/**
 * Returns rows removed, or -1 on error.
 */
int32_t wf_remove_empty_rows(WfDoc *d, uint32_t si, uint32_t r0, uint32_t r1);

int32_t wf_remove_duplicates(WfDoc *d,
                             uint32_t si,
                             uint32_t r0,
                             uint32_t r1,
                             const uint32_t *cols,
                             uint32_t ncols);

/**
 * how: 0 trim, 1 UPPER, 2 lower, 3 Title
 */
int32_t wf_transform(WfDoc *d, uint32_t si, const WfRect *rs, uint32_t n, uint32_t how);

/**
 * order: 0 D/M/Y, 1 M/D/Y, 2 Y/M/D
 */
int32_t wf_normalize_dates(WfDoc *d,
                           uint32_t si,
                           const WfRect *rs,
                           uint32_t n,
                           uint32_t order,
                           const char *fmt);

int32_t wf_normalize_amounts(WfDoc *d,
                             uint32_t si,
                             const WfRect *rs,
                             uint32_t n,
                             bool decimal_comma,
                             const char *fmt);

int32_t wf_text_to_columns(WfDoc *d,
                           uint32_t si,
                           uint32_t col,
                           uint32_t r0,
                           uint32_t r1,
                           const char *delim);

/**
 * flags: 1 match case, 2 whole cell, 4 search formulas
 */
bool wf_find(WfDoc *d,
             uint32_t si,
             uint32_t r,
             uint32_t c,
             const char *query,
             uint32_t flags,
             bool forward,
             uint32_t *r_out,
             uint32_t *c_out);

/**
 * All matches as (row, col) pairs written to `out` (2 u32 per match); returns the count.
 */
uint32_t wf_find_all(WfDoc *d,
                     uint32_t si,
                     const char *query,
                     uint32_t flags,
                     uint32_t *outp,
                     uint32_t max);

uint32_t wf_count_matches(WfDoc *d, uint32_t si, const char *query, uint32_t flags);

bool wf_replace_one(WfDoc *d,
                    uint32_t si,
                    uint32_t r,
                    uint32_t c,
                    const char *query,
                    const char *with_,
                    uint32_t flags);

int32_t wf_replace_all(WfDoc *d, uint32_t si, const char *query, const char *with_, uint32_t flags);

/**
 * Distinct values of a column as "value\tcount\n" lines.
 */
const char *wf_filter_values(WfDoc *d, uint32_t si, uint32_t header, uint32_t col, uint32_t limit);

/**
 * mode: 0 clear this column, 1 values (payload = "\n"-joined), 2 contains, 3 blanks only, 4 non-blanks.
 * Returns rows hidden.
 */
uint32_t wf_set_filter(WfDoc *d,
                       uint32_t si,
                       uint32_t header,
                       uint32_t col,
                       uint32_t mode,
                       const char *payload);

void wf_clear_filters(WfDoc *d, uint32_t si);

bool wf_filter_active(WfDoc *d, uint32_t si, uint32_t col);

void wf_stats(WfDoc *d, uint32_t si, const WfRect *rs, uint32_t n, WfStats *outp);

/**
 * Copy a rectangle: returns tab-separated text and keeps an internal clip.
 */
const char *wf_copy(WfDoc *d, uint32_t si, WfRect rect);

/**
 * Paste the internal clip copied from this document. what: 0 all, 1 values, 2 formats.
 */
bool wf_paste_clip(WfDoc *d, uint32_t si, WfRect target, uint32_t what, WfRect *out_rect);

bool wf_paste_text(WfDoc *d,
                   uint32_t si,
                   uint32_t r,
                   uint32_t c,
                   const char *text,
                   WfRect *out_rect);

#endif  /* WAFFLE_H */
